dist: bionic
osx_image: xcode11
os:
  - linux
  - osx
env:
  - TOR=false
  - TOR=true
language: node_js
node_js: '12'
cache:
  apt: true
  yarn: true
  brew: true
  npm: false
addons:
  homebrew:
    packages:
      - tor
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install tor; fi
  - npm ci
